import type { Episode, Title } from "./types";

const yt = (id: string) => `youtube:${id}`;

/** Bump this to force a catalog reseed of known titles. */
export const CATALOG_REVISION = "2026-09-13-latest";

export const RETIRED_SEED_IDS = [
  "sintel",
  "big-buck-bunny",
  "tears-of-steel",
  "elephants-dream",
  "his-girl-friday",
  "nosferatu",
  "carnival-of-souls",
  "house-on-haunted-hill",
  "abraham-lincoln",
  "dressed-to-kill",
  "suddenly",
  "pied-piper",
  "chaplin-festival",
  "sita-sings-the-blues",
  "three-stooges",
  "chrome-reels",
  "open-worlds",
  "night-of-the-living-dead",
  "plan-9",
  "charade",
  "the-general",
  "onenight",
  "digger",
  "dogstars",
  "jumanji",
  "insidious",
  "motu",
];

type Seed = Omit<
  Title,
  "posterUrl" | "backdropUrl" | "videoUrl" | "seasons" | "episodes" | "original"
> & {
  ytId: string;
  seasons?: number;
  episodes?: Episode[];
  original?: boolean;
};

function title({ ytId, seasons, episodes, original, ...rest }: Seed): Title {
  return {
    ...rest,
    posterUrl: `/posters/${rest.id}.jpg`,
    backdropUrl: `/backdrops/${rest.id}.jpg`,
    videoUrl: yt(ytId),
    seasons: seasons ?? 1,
    original: original ?? false,
    episodes: episodes ?? [],
  };
}

export const SEED_TITLES: Title[] = [
  title({
    id: "odyssey",
    name: "The Odyssey",
    synopsis:
      "Christopher Nolan’s IMAX epic of Homer — a warrior’s long road home across gods, monsters, and the wine-dark sea.",
    kind: "drama",
    genres: ["Epic", "Adventure", "Fantasy"],
    year: 2026,
    rating: "PG-13",
    durationMin: 173,
    matchScore: 99,
    featured: true,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "f_bKjZeJBBI",
  }),
  title({
    id: "spiderman",
    name: "Spider-Man: Brand New Day",
    synopsis:
      "The world forgot Peter Parker. He has not forgotten them — and a new threat is one he cannot even see.",
    kind: "movie",
    genres: ["Action", "Superhero", "Adventure"],
    year: 2026,
    rating: "PG-13",
    durationMin: 145,
    matchScore: 98,
    featured: true,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "62bIsvRcPv0",
  }),
  title({
    id: "doomsday",
    name: "Avengers: Doomsday",
    synopsis:
      "Heroes from three universes collide as Doctor Doom arrives. Earth’s mightiest may not be enough.",
    kind: "movie",
    genres: ["Action", "Superhero", "Sci-Fi"],
    year: 2026,
    rating: "PG-13",
    durationMin: 150,
    matchScore: 97,
    featured: true,
    trending: true,
    isNew: true,
    comingSoon: true,
    ytId: "irVNGjRFZGk",
  }),
  title({
    id: "hailmary",
    name: "Project Hail Mary",
    synopsis:
      "A junior-high science teacher wakes up 11.9 light-years from home with one job: save every sun like ours.",
    kind: "movie",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    year: 2026,
    rating: "PG-13",
    durationMin: 140,
    matchScore: 98,
    featured: true,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "m08TxIsFTRI",
  }),
  title({
    id: "superman",
    name: "Superman",
    synopsis:
      "James Gunn’s new DCU begins: Clark Kent must choose who he is — not just what he can do — as a darker world looks up.",
    kind: "movie",
    genres: ["Action", "Superhero", "Sci-Fi"],
    year: 2025,
    rating: "PG-13",
    durationMin: 129,
    matchScore: 96,
    featured: true,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "Ox8ZLF6cGM0",
  }),
  title({
    id: "avatar",
    name: "Avatar: Fire and Ash",
    synopsis:
      "James Cameron returns to Pandora. Jake and Neytiri face a people who answer fire with fire.",
    kind: "movie",
    genres: ["Sci-Fi", "Adventure", "Action"],
    year: 2025,
    rating: "PG-13",
    durationMin: 197,
    matchScore: 97,
    featured: true,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "nb_fFj_0rq8",
  }),
  title({
    id: "f1",
    name: "F1",
    synopsis:
      "Brad Pitt is a Formula 1 legend pulled out of exile to save a collapsing team — shot during real Grand Prix weekends.",
    kind: "drama",
    genres: ["Sports", "Action", "Drama"],
    year: 2025,
    rating: "PG-13",
    durationMin: 155,
    matchScore: 97,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "CT2_P2DZBR0",
  }),
  title({
    id: "sinners",
    name: "Sinners",
    synopsis:
      "Ryan Coogler and Michael B. Jordan. Twin brothers go home to start again — and something older follows them back.",
    kind: "drama",
    genres: ["Horror", "Drama", "Thriller"],
    year: 2025,
    rating: "R",
    durationMin: 137,
    matchScore: 99,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "bKGxHflevuk",
  }),
  title({
    id: "fantasticfour",
    name: "The Fantastic Four: First Steps",
    synopsis:
      "Marvel’s first family in a retro-future world — and a hungry god named Galactus at the door.",
    kind: "movie",
    genres: ["Action", "Superhero", "Sci-Fi"],
    year: 2025,
    rating: "PG-13",
    durationMin: 115,
    matchScore: 94,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "pAsmrKyMqaA",
  }),
  title({
    id: "toystory5",
    name: "Toy Story 5",
    synopsis:
      "The toys return as a new kind of play — screens, not shelves — threatens what it means to be a child’s favorite.",
    kind: "movie",
    genres: ["Animation", "Family", "Comedy"],
    year: 2026,
    rating: "G",
    durationMin: 100,
    matchScore: 95,
    featured: false,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "n41enLMUrgU",
  }),
  title({
    id: "mario",
    name: "The Super Mario Galaxy Movie",
    synopsis:
      "Mario and Luigi are launched past the Mushroom Kingdom into a cosmos of stars, gravity, and Bowser’s biggest plan yet.",
    kind: "movie",
    genres: ["Animation", "Family", "Adventure"],
    year: 2026,
    rating: "PG",
    durationMin: 100,
    matchScore: 96,
    featured: false,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "vFeJf5QMzJU",
  }),
  title({
    id: "supergirl",
    name: "Supergirl",
    synopsis:
      "Kara Zor-El is not her cousin. A jaded survivor of Krypton cuts a violent path across the stars.",
    kind: "movie",
    genres: ["Action", "Superhero", "Sci-Fi"],
    year: 2026,
    rating: "PG-13",
    durationMin: 130,
    matchScore: 94,
    featured: false,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "mlfzhW4tq5Q",
  }),
  title({
    id: "wicked",
    name: "Wicked: For Good",
    synopsis:
      "Elphaba and Glinda finish the story — friendship, power, and the making of a wicked legend.",
    kind: "drama",
    genres: ["Musical", "Fantasy", "Romance"],
    year: 2025,
    rating: "PG",
    durationMin: 137,
    matchScore: 98,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "vt98AlBDI9Y",
  }),
  title({
    id: "jurassic",
    name: "Jurassic World Rebirth",
    synopsis:
      "A new expedition sails toward dinosaurs that have grown rarer, smarter, and much less interested in being studied.",
    kind: "movie",
    genres: ["Action", "Sci-Fi", "Adventure"],
    year: 2025,
    rating: "PG-13",
    durationMin: 133,
    matchScore: 93,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "jan5CFWs9ic",
  }),
  title({
    id: "mi",
    name: "Mission: Impossible – The Final Reckoning",
    synopsis:
      "Every choice Ethan Hunt has ever made lands here. The IMF’s last mission may also be its last day.",
    kind: "movie",
    genres: ["Action", "Spy", "Thriller"],
    year: 2025,
    rating: "PG-13",
    durationMin: 169,
    matchScore: 97,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "fsQgc9pCyDU",
  }),
  title({
    id: "zootopia2",
    name: "Zootopia 2",
    synopsis:
      "Judy and Nick follow a venomous new case into parts of the city no mammal was meant to see.",
    kind: "movie",
    genres: ["Animation", "Family", "Comedy"],
    year: 2025,
    rating: "PG",
    durationMin: 108,
    matchScore: 95,
    featured: false,
    trending: false,
    isNew: false,
    comingSoon: false,
    ytId: "BjkIOU5PhyQ",
  }),
  title({
    id: "httyd",
    name: "How to Train Your Dragon",
    synopsis:
      "A live-action Berk: Hiccup befriends a Night Fury and tries to end a war his father was born to fight.",
    kind: "movie",
    genres: ["Adventure", "Family", "Fantasy"],
    year: 2025,
    rating: "PG",
    durationMin: 125,
    matchScore: 94,
    featured: false,
    trending: false,
    isNew: false,
    comingSoon: false,
    ytId: "22w7z_lT6YM",
  }),
  title({
    id: "minecraft",
    name: "A Minecraft Movie",
    synopsis:
      "Four misfits fall through a portal into the Overworld, where imagination is the only way out.",
    kind: "movie",
    genres: ["Adventure", "Family", "Comedy"],
    year: 2025,
    rating: "PG",
    durationMin: 101,
    matchScore: 91,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "wJO_vIDZn-I",
  }),
  title({
    id: "years28",
    name: "28 Years Later",
    synopsis:
      "Danny Boyle and Alex Garland return. The rage virus still holds Britain — and the infected have changed.",
    kind: "movie",
    genres: ["Horror", "Thriller", "Sci-Fi"],
    year: 2025,
    rating: "R",
    durationMin: 115,
    matchScore: 95,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "mcvLKldPM08",
  }),
  title({
    id: "tron",
    name: "Tron: Ares",
    synopsis:
      "A program is sent from the Grid into the real world. Humankind’s first encounter with a being of code.",
    kind: "movie",
    genres: ["Sci-Fi", "Action", "Thriller"],
    year: 2025,
    rating: "PG-13",
    durationMin: 119,
    matchScore: 90,
    featured: false,
    trending: false,
    isNew: false,
    comingSoon: false,
    ytId: "YShVEXb7-ic",
  }),
  title({
    id: "thunderbolts",
    name: "Thunderbolts*",
    synopsis:
      "Not super. Not heroes. Marvel’s antiheroes get one last shot at redemption — or at each other.",
    kind: "movie",
    genres: ["Action", "Superhero", "Drama"],
    year: 2025,
    rating: "PG-13",
    durationMin: 126,
    matchScore: 93,
    featured: false,
    trending: true,
    isNew: false,
    comingSoon: false,
    ytId: "-sAOWhvheK8",
  }),
  title({
    id: "hunger",
    name: "The Hunger Games: Sunrise on the Reaping",
    synopsis:
      "Twenty-four years before Katniss — Haymitch Abernathy walks into the Second Quarter Quell.",
    kind: "drama",
    genres: ["Dystopia", "Action", "Drama"],
    year: 2026,
    rating: "PG-13",
    durationMin: 140,
    matchScore: 96,
    featured: false,
    trending: true,
    isNew: true,
    comingSoon: true,
    ytId: "fS35YSjopjE",
  }),
  title({
    id: "mk2",
    name: "Mortal Kombat II",
    synopsis:
      "Earthrealm’s champions return as the tournament spills off the island and into a war of realms.",
    kind: "movie",
    genres: ["Action", "Fantasy", "Martial Arts"],
    year: 2026,
    rating: "R",
    durationMin: 122,
    matchScore: 91,
    featured: false,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "-TjLBB5Ny6k",
  }),
  title({
    id: "scream7",
    name: "Scream 7",
    synopsis:
      "Ghostface is back, and this time the rules of the franchise are the weapon.",
    kind: "movie",
    genres: ["Horror", "Thriller", "Mystery"],
    year: 2026,
    rating: "R",
    durationMin: 118,
    matchScore: 90,
    featured: false,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "UEzhbCUTxlM",
  }),
  title({
    id: "prada2",
    name: "The Devil Wears Prada 2",
    synopsis:
      "Andy is back in Miranda’s orbit — older, sharper, and still not dressed for the weather.",
    kind: "drama",
    genres: ["Comedy", "Drama", "Fashion"],
    year: 2026,
    rating: "PG-13",
    durationMin: 118,
    matchScore: 93,
    featured: false,
    trending: false,
    isNew: true,
    comingSoon: false,
    ytId: "e9HXmMnUEdE",
  }),
  title({
    id: "stranger",
    name: "Stranger Things",
    synopsis:
      "The final season. Hawkins is locked down, Eleven is in hiding, and Vecna is done playing campaigns.",
    kind: "series",
    genres: ["Sci-Fi", "Horror", "Drama"],
    year: 2025,
    rating: "TV-14",
    durationMin: 70,
    seasons: 5,
    matchScore: 99,
    featured: false,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "PssKpzB0Ah0",
    episodes: [
      {
        id: "st-1",
        season: 5,
        episode: 1,
        name: "The Crawl",
        synopsis: "The party hunts Vecna as Hawkins collapses inward.",
        durationMin: 70,
        videoUrl: yt("PssKpzB0Ah0"),
      },
      {
        id: "st-2",
        season: 5,
        episode: 2,
        name: "Chapter Two",
        synopsis: "One last fight for the days on the other side of this.",
        durationMin: 80,
        videoUrl: yt("AfQ13jsLDms"),
      },
    ],
  }),
  title({
    id: "severance",
    name: "Severance",
    synopsis:
      "Season two: Mark and his innies learn what it costs to touch the barrier between work and the rest of a life.",
    kind: "series",
    genres: ["Thriller", "Drama", "Mystery"],
    year: 2025,
    rating: "TV-MA",
    durationMin: 55,
    seasons: 2,
    matchScore: 98,
    featured: false,
    trending: true,
    isNew: true,
    comingSoon: false,
    ytId: "_UXKlYvLGJY",
    episodes: [
      {
        id: "sev-1",
        season: 2,
        episode: 1,
        name: "Good News About Hell",
        synopsis: "Hope this finds you well.",
        durationMin: 55,
        videoUrl: yt("_UXKlYvLGJY"),
      },
    ],
  }),
];
