/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DramasRouteImport } from './routes/dramas'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as TitleIdRouteImport } from './routes/title.$id'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DramasRoute = DramasRouteImport.update({
  id: '/dramas',
  path: '/dramas',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleIdRoute = TitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dramas': typeof DramasRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/title/$id': typeof TitleIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dramas': typeof DramasRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/title/$id': typeof TitleIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dramas': typeof DramasRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/title/$id': typeof TitleIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dramas'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/series'
    | '/admin/login'
    | '/title/$id'
    | '/watch/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dramas'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/series'
    | '/admin/login'
    | '/title/$id'
    | '/watch/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/dramas'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/series'
    | '/admin/login'
    | '/title/$id'
    | '/watch/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DramasRoute: typeof DramasRoute
  MoviesRoute: typeof MoviesRoute
  MyListRoute: typeof MyListRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  TitleIdRoute: typeof TitleIdRoute
  WatchIdRoute: typeof WatchIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dramas': {
      id: '/dramas'
      path: '/dramas'
      fullPath: '/dramas'
      preLoaderRoute: typeof DramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$id': {
      id: '/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof TitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DramasRoute: DramasRoute,
  MoviesRoute: MoviesRoute,
  MyListRoute: MyListRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  TitleIdRoute: TitleIdRoute,
  WatchIdRoute: WatchIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
